const barChairsPosition = [
  {
    positionTop: "13%",
    positionLeft: "26.5%",
    rotation: null,
    numberRotation: null,
    numberPaddingRight: null,
    id: "barSpot1",
  },
  {
    positionTop: "20%",
    positionLeft: "26.5%",
    rotation: null,
    numberRotation: null,
    numberPaddingRight: null,
    id: "barSpot2",
  },
  {
    positionTop: "28%",
    positionLeft: "30%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot3",
  },
  {
    positionTop: "28%",
    positionLeft: "34.4%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot4",
  },
  {
    positionTop: "28%",
    positionLeft: "38.4%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot5",
  },
  {
    positionTop: "28%",
    positionLeft: "42.5%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot6",
  },
  {
    positionTop: "28%",
    positionLeft: "46.4%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot7",
  },
  {
    positionTop: "28%",
    positionLeft: "50.6%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot8",
  },
  {
    positionTop: "28%",
    positionLeft: "55%",
    rotation: "270deg",
    numberRotation: "90deg",
    numberPaddingRight: null,
    id: "barSpot9",
  },
];

export default barChairsPosition;
